Traceback (most recent call last):
  File "/nix/store/zsn8q983hf8ca7nr5bz8zlbx8i56pa9p-letsencrypt-0.1.0/bin/..letsencrypt-wrapped-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/zsn8q983hf8ca7nr5bz8zlbx8i56pa9p-letsencrypt-0.1.0/lib/python2.7/site-packages/letsencrypt/cli.py", line 1251, in main
    setup_logging(args, _cli_log_handler, logfile='letsencrypt.log')
  File "/nix/store/zsn8q983hf8ca7nr5bz8zlbx8i56pa9p-letsencrypt-0.1.0/lib/python2.7/site-packages/letsencrypt/cli.py", line 1164, in setup_logging
    args, logfile=logfile, fmt=fmt)
  File "/nix/store/zsn8q983hf8ca7nr5bz8zlbx8i56pa9p-letsencrypt-0.1.0/lib/python2.7/site-packages/letsencrypt/cli.py", line 1135, in setup_log_file_handler
    log_file_path, maxBytes=2 ** 20, backupCount=10)
  File "/nix/store/ccmyi36pqr600f2bq7nivbahnczkfqf3-python-2.7.11/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/nix/store/ccmyi36pqr600f2bq7nivbahnczkfqf3-python-2.7.11/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/nix/store/ccmyi36pqr600f2bq7nivbahnczkfqf3-python-2.7.11/lib/python2.7/logging/__init__.py", line 905, in __init__
    StreamHandler.__init__(self, self._open())
  File "/nix/store/ccmyi36pqr600f2bq7nivbahnczkfqf3-python-2.7.11/lib/python2.7/logging/__init__.py", line 935, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/log/letsencrypt/letsencrypt.log'
